<a href="https://colab.research.google.com/github/SpellOnYou/CLab21/blob/main/dummymodule/2021_05_06_teamlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. forward 
2. backward
3. 

In [1]:
!wc /content/CLab21/data/emotions/isear/isear-val.csv

  1150  25264 139578 /content/CLab21/data/emotions/isear/isear-val.csv


In [32]:
# suppose we have (n=inputdata, m=maxlength) / traub 5000 vakd=ud 1159
n, m = 5000, 100
h = 50
c = 10

for now will not use any initialization methods like
- [xavier](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)
- [kaiming](https://arxiv.org/pdf/1502.01852.pdf)

In [33]:
import torch
w1 = torch.randn(m, h)
w2 = torch.randn(h, c)
b1 = torch.randn(h)
b2 = torch.randn(c)

- make dummy data

In [34]:
import random

In [35]:
dummy_x = torch.randn(n, m)
dummy_y = torch.zeros(n, c)
dummy_y[range(n), random.choices(range(10), k=n)] =1

In [47]:
dummy_x.mean(), dummy_x.std()

(tensor(0.0002), tensor(1.0007))

In [36]:
dummy_x.shape, dummy_y.shape

(torch.Size([5000, 100]), torch.Size([5000, 10]))

In [37]:
#see the sample
dummy_x[:2], dummy_y[:2]

(tensor([[-5.0657e-01, -1.8019e+00, -9.4913e-02, -3.1061e+00,  1.5904e+00,
           8.9199e-01,  3.0894e-01, -2.4862e-01,  7.1875e-01,  5.8834e-02,
          -3.1210e-01, -1.4977e-01,  1.0126e+00, -3.7097e-01, -2.6162e-01,
           9.8891e-02,  2.3136e-02,  1.4616e-02, -4.3619e-01, -3.4526e-01,
          -7.5891e-01, -2.6761e-03,  1.4875e-02, -7.9154e-02, -9.0084e-01,
          -1.1934e+00,  1.1234e+00,  6.7298e-02,  6.4309e-01, -9.7637e-01,
           1.2800e+00,  4.8565e-01, -1.6111e-01, -1.7781e+00, -1.2607e+00,
          -7.7666e-01, -2.7573e-01,  6.7721e-01,  4.5730e-01,  3.4407e-01,
           4.1272e-01, -3.3337e-01, -3.3374e-01, -1.3198e-01,  2.3816e-02,
           7.7659e-01,  7.4477e-01, -3.7002e-01,  2.2400e-01,  2.9074e-01,
          -1.1658e+00, -4.2135e-01,  4.7339e-01, -1.5727e-02, -9.4095e-02,
          -7.1008e-01, -1.2635e+00,  4.8978e-02,  2.6873e-01,  9.0145e-01,
           1.3043e+00, -5.6530e-01,  1.1302e-01,  2.3972e-02, -1.2756e+00,
           1.2655e+00, -6

- make this as function

In [61]:
def init_data():
    x = torch.randn(n, m)
    y = torch.zeros(n, c)
    y[range(n), random.choices(range(10), k=n)] =1    
    return x, y

keep this for later
```
class Linear():
    def __init__(self, w, b):
        self.w, self.b = w, b
    def forward(self, x):
        self.out = x@w+b
class Relu():
    def forward(self, x):
        self.out = self.clamp_min(x)
class CrossEntropy():
    pass    
```

In [59]:
def linear(x, w, b):
    return x@w +b
def relu(x, mu=0):
    return x.clamp_min(0.) -mu
def softmax(x):
    return (x.exp()/ x.exp().sum(-1, keepdim=True))

In [39]:
lin1 = linear(dummy_x, w1, b1)

In [40]:
lin1.shape

torch.Size([5000, 50])

In [41]:
a1 = relu(lin1)
lin2 = linear(a1, w2, b2)

In [42]:
a1.mean(), a1.std() #quite big T.T.. we need to introduce norm method.. lalter

(tensor(3.9345), tensor(5.7903))

In [43]:
lin2.shape

torch.Size([5000, 10])

In [44]:
out = softmax(lin2)

In [45]:
out[:10]

tensor([[-6.2238e+00, -9.2491e+01, -6.7284e+01, -5.8517e+01, -8.6641e+01,
         -6.5940e+01, -1.9836e-03, -8.9085e+01, -6.0520e+01,        -inf],
        [        nan,        -inf,        -inf,        -inf,        -inf,
                -inf,        -inf,        -inf,        -inf,        -inf],
        [-2.5412e+01, -6.3892e+00, -3.9197e-01,        -inf, -2.0100e+01,
         -5.9749e+01, -1.1314e+00, -3.2975e+01, -1.8035e+01, -8.0769e+01],
        [-3.6956e-05, -4.7363e+01, -1.9230e+01, -1.1031e+01, -6.4294e+01,
         -9.2967e+01, -1.0782e+01, -5.9550e+01, -7.4302e+01, -8.6915e+01],
        [-4.7989e+01, -2.0606e+01, -1.7268e+01,        -inf,        -inf,
         -8.0262e+01, -5.9605e-08, -7.6601e+01, -3.6668e+01, -1.0071e+02],
        [-2.4284e+01, -1.0006e+02, -2.3485e-05, -8.7749e+01, -1.0660e+01,
         -2.4100e+01, -5.2645e+01, -6.9549e+01, -8.0756e+01,        -inf],
        [-1.9809e+01,  0.0000e+00, -1.7215e+01, -5.2763e+01, -9.3995e+01,
                -inf, -8.6620e+0

In [29]:
dummy_y.max(dim=1).indices #label

tensor([4, 9, 8,  ..., 3, 5, 5])

In [30]:
out[range(out.shape[0]), dummy_y.max(dim=1).indices]

tensor([  0.0000,     -inf,     -inf,  ...,     -inf, -36.8967, -36.4830])

In [54]:
def cross_entropy(y, yhat):
    return (yhat.log()[range(yhat.shape[0]), y.max(dim=1).indices]).mean()

In [55]:
loss = cross_entropy(out, dummy_y)

In [56]:
loss

tensor(-inf)

---

- I got -inf loss...... let me try kaiming init + relu mean modification

In [57]:
import math

In [58]:
w1 = torch.randn(m, h) / math.sqrt(h)
w2 = torch.randn(h, c) / math.sqrt(c)
b1 = torch.randn(h)
b2 = torch.randn(c)

In [60]:
from functools import partial
relu2 = partial(relu, mu=0.5)

In [62]:
dummy_x2, dummy_y2 = init_data()

In [65]:
lin1_2 = linear(dummy_x2, w1, b1)
a2 = relu2(lin1_2)
lin2_2 = linear(a2, w2, b2)
out2 = softmax(lin2_2)

In [66]:
out2[:10] #this seem much better :)

tensor([[3.1497e-01, 4.9887e-02, 3.9724e-03, 7.2713e-02, 2.1319e-01, 3.8921e-02,
         2.8901e-02, 2.3906e-01, 2.1904e-02, 1.6479e-02],
        [8.6601e-01, 1.2302e-03, 2.2501e-04, 1.0445e-01, 3.2023e-03, 9.3809e-04,
         1.4640e-02, 6.9775e-03, 1.0336e-03, 1.2944e-03],
        [1.8768e-01, 4.1592e-02, 8.8009e-04, 1.7167e-01, 7.3062e-02, 6.9389e-02,
         2.0415e-01, 6.6745e-02, 1.3770e-01, 4.7142e-02],
        [5.1205e-02, 8.3358e-04, 1.7003e-03, 3.4740e-01, 8.7307e-02, 6.6863e-02,
         2.0067e-01, 2.3603e-03, 1.8758e-01, 5.4083e-02],
        [8.5319e-01, 4.4327e-02, 6.6672e-05, 7.3856e-02, 1.1946e-02, 3.1689e-03,
         6.4267e-03, 2.1462e-04, 3.4284e-04, 6.4570e-03],
        [2.7209e-01, 1.8657e-02, 5.1879e-03, 1.7417e-01, 2.1907e-01, 1.4561e-02,
         1.2087e-01, 1.6391e-02, 3.1483e-02, 1.2753e-01],
        [3.9201e-02, 3.8379e-03, 5.6551e-04, 3.2937e-01, 4.8916e-01, 6.6830e-02,
         3.5940e-03, 4.9645e-02, 9.2131e-03, 8.5757e-03],
        [2.7155e-01, 3.6997

In [67]:
cross_entropy(dummy_y2, out2)

tensor(-4.1377)

- fair enough