<a href="https://colab.research.google.com/github/SpellOnYou/CLab21/blob/main/dummymodule/2021_05_06_teamlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# suppose we have (n=inputdata, m=maxlength) / traub 5000 vakd=ud 1159
n, m = 5000, 100
h = 50
c = 10

for now will not use any initialization methods like
- [xavier](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)
- [kaiming](https://arxiv.org/pdf/1502.01852.pdf)

In [4]:
import torch
w1 = torch.randn(m, h)
w2 = torch.randn(h, c)
b1 = torch.randn(h)
b2 = torch.randn(c)

## without normalization/init method

- make dummy data

In [5]:
import random

In [6]:
dummy_x = torch.randn(n, m)
dummy_y = torch.zeros(n, c)
dummy_y[range(n), random.choices(range(10), k=n)] =1

In [7]:
dummy_x.mean(), dummy_x.std()

(tensor(-0.0015), tensor(0.9985))

In [8]:
dummy_x.shape, dummy_y.shape

(torch.Size([5000, 100]), torch.Size([5000, 10]))

In [9]:
#see the sample
dummy_x[:2], dummy_y[:2]

(tensor([[ 1.7072e+00, -1.5670e+00, -1.3663e+00, -7.8767e-01,  4.2144e-01,
          -1.5878e-01, -4.6477e-01, -2.6849e-01,  7.2228e-01, -1.2552e+00,
           4.9191e-02, -1.4516e+00, -5.2243e-01,  7.2120e-02,  1.6832e+00,
           6.3907e-01,  6.4258e-01, -1.2559e+00, -3.2130e-01, -1.0986e+00,
          -6.3865e-01, -1.0188e-01, -7.7652e-01,  4.9091e-01,  2.0244e+00,
           1.2449e-02,  8.0138e-01,  7.5497e-02, -1.2243e-01, -1.3913e+00,
           1.0774e+00, -2.5654e-01,  1.4311e+00, -1.3952e+00,  1.9716e+00,
           1.5850e-01, -1.1022e+00, -9.5781e-01, -5.8858e-02,  9.2348e-01,
           2.7748e-01,  1.0486e+00, -1.7238e+00, -1.7909e+00, -7.6187e-01,
           1.1606e+00,  2.9815e-01, -4.4967e-01,  1.1932e+00, -1.8211e-01,
           6.5096e-01, -9.0922e-01, -6.9057e-01, -7.3239e-01,  1.1684e+00,
          -2.7499e-01,  1.0999e+00, -9.9993e-01,  9.1430e-01, -7.2204e-02,
           6.4324e-01,  1.5330e+00, -1.2818e+00, -2.7243e-01, -7.1434e-01,
          -1.1578e+00,  3

- make this as function

In [10]:
def init_data():
    x = torch.randn(n, m)
    y = torch.zeros(n, c)
    y[range(n), random.choices(range(10), k=n)] =1    
    return x, y

keep this for later
```
class Linear():
    def __init__(self, w, b):
        self.w, self.b = w, b
    def forward(self, x):
        self.out = x@w+b
class Relu():
    def forward(self, x):
        self.out = self.clamp_min(x)
class CrossEntropy():
    pass    
```

In [11]:
def linear(x, w, b):
    return x@w +b
def relu(x, mu=0):
    return x.clamp_min(0.) -mu
def softmax(x):
    return (x.exp()/ x.exp().sum(-1, keepdim=True))

In [12]:
lin1 = linear(dummy_x, w1, b1)

In [13]:
lin1.shape

torch.Size([5000, 50])

In [14]:
a1 = relu(lin1)
lin2 = linear(a1, w2, b2)

In [15]:
a1.mean(), a1.std() #quite big T.T.. we need to introduce norm method.. lalter

(tensor(3.9064), tensor(5.8161))

In [16]:
lin2.shape

torch.Size([5000, 10])

In [17]:
out = softmax(lin2)

In [18]:
out[:10]

tensor([[4.6825e-26, 0.0000e+00, 0.0000e+00, 2.0833e-14, 5.4882e-25, 3.0740e-32,
         2.5673e-34, 7.7257e-01, 2.8270e-41, 2.2743e-01],
        [1.1176e-02, 2.1977e-41, 0.0000e+00, 1.5835e-43, 7.3346e-21, 9.1683e-29,
         6.1376e-10, 9.8882e-01, 3.2384e-36, 4.3025e-10],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00,        nan, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00,        nan, 0.0000e+00, 0.0000e+00],
        [4.9987e-40, 0.0000e+00, 0.0000e+00, 5.7263e-20, 0.0000e+00, 2.1633e-22,
         0.0000e+00, 1.0000e+00, 0.0000e+00, 1.8492e-17],
        [1.0666e-34, 0.0000e+00, 0.0000e+00, 1.0000e+00, 8.0386e-24, 0.0000e+00,
         1.4253e-32, 1.7550e-14, 5.7872e-41, 2.8909e-08],
        [2.0190e-40, 0.0000e+00, 0.0000e+00, 2.1542e-32, 4.2039e-45, 0.0000e+00,
         7.7887e-09, 1.0000e+00, 6.0531e-40, 5.6373e-35],
        [1.7516e-43, 0.0000

In [19]:
dummy_y.max(dim=1).indices #label

tensor([8, 8, 7,  ..., 4, 5, 6])

In [20]:
out[range(out.shape[0]), dummy_y.max(dim=1).indices]

tensor([2.8270e-41, 3.2384e-36,        nan,  ..., 0.0000e+00, 0.0000e+00,
        2.7962e-22])

In [21]:
def cross_entropy(y, yhat):
    return (yhat.log()[range(yhat.shape[0]), y.max(dim=1).indices]).mean()

In [22]:
loss = cross_entropy(out, dummy_y)

In [23]:
loss

tensor(-inf)

---

## with normalization (kaiming) / relu - 0.5

- I got -inf loss...... let me try kaiming init + relu mean modification

In [24]:
import math

In [25]:
w1 = torch.randn(m, h) / math.sqrt(h)
w2 = torch.randn(h, c) / math.sqrt(c)
b1 = torch.randn(h)
b2 = torch.randn(c)

In [26]:
from functools import partial
relu2 = partial(relu, mu=0.5)

In [53]:
dummy_x2, dummy_y2 = init_data()

In [54]:
lin1_2 = linear(dummy_x2, w1, b1)
a2 = relu2(lin1_2)
lin2_2 = linear(a2, w2, b2)
out2 = softmax(lin2_2)

In [55]:
loss = cross_entropy(dummy_y2, out2)

- fair enough

## backward

In [34]:
def mse_grad(inp, trg): inp.g= (inp.squeeze(-1)-trg).unsqueeze(-1)*(2/inp.shape[0])

In [35]:
def lin_grad(inp, out, w, b):
    inp.g = out.g @ w.t()
    w.g = (inp.unsqueeze(-1) * out.g.unsqueeze(1)).sum(0) # / inp.shape[0] -> why we don't need this?
    b.g = out.g.sum(0)

In [36]:
def relu_grad(inp, out): inp.g = out.g* (inp>0).float()

In [37]:
def softmax_grad(inp, out): inp.g = (1-out.g)*out.g

In [51]:
def ce_grad(y, yhat, out): yhat.g = yhat - y

In [56]:
ce_grad(dummy_y2, out2, loss)
softmax_grad(lin2_2, out2)
lin_grad(a2, lin2_2, w2, b2)
relu_grad(lin1_2, a2)
lin_grad(dummy_x2, lin1_2, w1, b1)

----

## refactoring

In [32]:
class Linear():
    def __init__(w, b):
        self.w, self.b = w, b
    def forward(x): 
        self.out = x@self.w + self.b
        return self.out

In [ ]:
class Relu():
    def forward(x):
        